/* v1.23 game systems */
(function () {
  if (window.__cbFeat23) return;
  window.__cbFeat23 = true;
  function naira(n){var v=Math.max(0,Math.round(Number(n)||0));return '₦'+v.toLocaleString();}
  function nairaSigned(n){var v=Math.round(Number(n)||0);var a='₦'+Math.abs(v).toLocaleString();return v>0?'+'+a:v<0?'−'+a:a;}
  window.formatNotes=naira;window.formatNotesSigned=nairaSigned;
  var ctx=null,lastPay=null;
  function unlock(){try{if(!ctx)ctx=new (window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended')ctx.resume();}catch(e){}}
  document.addEventListener('pointerdown',unlock,{once:true});
  function beep(f,d,t,g){if(!ctx)return;try{var o=ctx.createOscillator(),a=ctx.createGain();o.type=t||'sine';o.frequency.value=f;a.gain.setValueAtTime(g||.07,ctx.currentTime);a.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+d);o.connect(a);a.connect(ctx.destination);o.start();o.stop(ctx.currentTime+d);}catch(e){}}
  function watchPay(){var el=document.getElementById('hud-pay');if(!el||el.__cb)return;el.__cb=1;new MutationObserver(function(){var v=parseInt((el.textContent||'').replace(/[^\d-]/g,''),10);if(isNaN(v))return;if(lastPay===null){lastPay=v;return;}if(v>lastPay){unlock();beep(880,.12,'triangle',.07);setTimeout(function(){beep(1320,.16,'sine',.05);},70);}else if(v<lastPay){unlock();beep(220,.18,'square',.05);}lastPay=v;}).observe(el,{childList:true,characterData:true,subtree:true});}
  function reason(r){if(!r)return 'No further note.';var a=(r.action||'').toUpperCase();if(r.correct){if(r.action==='approve')return a+' was lawful. Papers agreed with the bulletin.';if(r.action==='deny')return a+' was lawful. A discrepancy or ban was present.';if(r.action==='detain')return a+' was lawful. File met a detain condition.';return a+' matched standing orders.';}if(r.action==='approve')return 'APPROVE was incorrect.';if(r.action==='deny')return 'DENY was incorrect.';if(r.action==='detain')return 'DETAIN was incorrect.';return 'Action did not match the file.';}
  function modal(title,body){var m=document.getElementById('cb-detail-modal');if(!m){m=document.createElement('div');m.id='cb-detail-modal';m.innerHTML='<div class="cb-detail-card"><div class="cb-detail-kicker">FIBA FILE NOTE</div><div class="cb-detail-title"></div><div class="cb-detail-body"></div><button type="button" class="btn-primary" id="cb-detail-close">CLOSE</button></div>';document.body.appendChild(m);m.addEventListener('click',function(e){if(e.target===m||e.target.id==='cb-detail-close')m.classList.remove('open');});}m.querySelector('.cb-detail-title').textContent=title||'NOTE';m.querySelector('.cb-detail-body').textContent=body||'';m.classList.add('open');}
  function bindEod(){var box=document.getElementById('eod-pay-breakdown');if(!box||box.__cb)return;box.__cb=1;box.addEventListener('click',function(ev){var row=ev.target.closest('.eod-pay-row');if(!row)return;var results=(window.state&&state.dayResults)||[];var label=(row.querySelector('span')||{}).textContent||'';var hit=null;for(var i=0;i<results.length;i++){if(label.indexOf((results[i].name||'').split(' ')[0])!==-1){hit=results[i];break;}}modal(label,hit?(hit.name+' — '+String(hit.action||'').toUpperCase()+(hit.correct?' (upheld).':' (overturned).')+'\n\n'+reason(hit)+'\n\nTill: '+nairaSigned(hit.payChange||0)):'Household or grade charge.');});}
  var HOOKS=[{test:/relief|food|garri|rice/i,tag:'RELIEF',line:'A relief lorry is in the queue because of today\'s memo.'},{test:/press|journalist/i,tag:'PRESS',line:'A correspondent is at the window.'},{test:/medical|hospital|clinic/i,tag:'MEDICAL',line:'Someone holds a clinic letter.'},{test:/curfew|dusk|16:00/i,tag:'LATE',line:'The memo on hours is now a person in front of you.'},{test:/watch.?list|detain|infiltrat/i,tag:'WATCH',line:'A name on today\'s paper may be in this queue.'},{test:/tax|ticket/i,tag:'TAX',line:'The tax-ticket rule leans on the next folder.'},{test:/biafra|rising sun/i,tag:'BIAFRAN',line:'A rising-sun document is in circulation.'}];
  function memo(){var body=document.getElementById('bulletin-body');var text=body?body.innerText:'';if(!text||!window.state||!state.dayTravellers)return;var hook=null;for(var i=0;i<HOOKS.length;i++)if(HOOKS[i].test.test(text)){hook=HOOKS[i];break;}if(!hook)return;var t=state.dayTravellers[Math.min(2,state.dayTravellers.length-1)];if(t){t.memoHook=hook;}}
  function wrap(){if(typeof window.loadNextTraveller!=='function'||window.loadNextTraveller.__v23||window.loadNextTraveller.__v30)return;var prev=window.loadNextTraveller;window.loadNextTraveller=function(){prev.apply(this,arguments);try{var list=state.dayTravellers||[];var t=list[state.traveller]||list[state.traveller-1];if(t&&t.memoHook){var d=document.getElementById('tp-desc');if(d&&d.textContent.indexOf(t.memoHook.line)===-1)d.textContent=(d.textContent?d.textContent+' — ':'')+t.memoHook.line;}}catch(e){}};window.loadNextTraveller.__v23=true;if(prev.__v30)window.loadNextTraveller.__v30=true;}
  var css=document.createElement('style');css.textContent='#eod-report{padding-top:max(22px,env(safe-area-inset-top,0px))!important;max-height:100dvh;overflow-y:auto}#cb-detail-modal{display:none;position:fixed;inset:0;z-index:100010;background:rgba(10,13,7,.72);align-items:center;justify-content:center;padding:24px 16px}#cb-detail-modal.open{display:flex}.cb-detail-card{background:#F4E8C8;color:#1A2610;max-width:420px;width:100%;padding:20px}.cb-detail-body{white-space:pre-wrap;margin:10px 0 16px}.eod-pay-row{cursor:pointer}';document.head.appendChild(css);
  function tick(){window.formatNotes=naira;window.formatNotesSigned=nairaSigned;watchPay();bindEod();wrap();memo();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',tick);else tick();
  setInterval(tick,1500);
})();
